name: escoladominical
description: Aplicativo para gestão da Escola Dominical
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_auth_web: ^5.1.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_storage_web: ^3.10.12

  # Outras dependências
  table_calendar: ^3.1.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/flutter_logo.png
    - assets/images/cargando.png
    - assets/images/default_profile.png

flutter_native_splash:
  color: "#1a237e"
  image: assets/images/cargando.png
  android: true
  ios: true
  web: true