// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqsLRxXZyOrx1TqCYerJAne3TcNQn76as',
    appId: '1:371129962616:web:a6970c90e2721fafa29d8d',
    messagingSenderId: '371129962616',
    projectId: 'escoladominical-f0c5a',
    authDomain: 'escoladominical-f0c5a.firebaseapp.com',
    storageBucket: 'escoladominical-f0c5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCseRr2Zw2Mt3cociM6LDjtypJfzUq3ILM',
    appId: '1:371129962616:android:e7ef90286b569b56a29d8d',
    messagingSenderId: '371129962616',
    projectId: 'escoladominical-f0c5a',
    storageBucket: 'escoladominical-f0c5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmK7CGzU9pfDaA0b-obzjZVIRyeVMpC7g',
    appId: '1:371129962616:ios:d9fc7b4db40986e3a29d8d',
    messagingSenderId: '371129962616',
    projectId: 'escoladominical-f0c5a',
    storageBucket: 'escoladominical-f0c5a.firebasestorage.app',
    iosBundleId: 'com.example.escoladominical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmK7CGzU9pfDaA0b-obzjZVIRyeVMpC7g',
    appId: '1:371129962616:ios:d9fc7b4db40986e3a29d8d',
    messagingSenderId: '371129962616',
    projectId: 'escoladominical-f0c5a',
    storageBucket: 'escoladominical-f0c5a.firebasestorage.app',
    iosBundleId: 'com.example.escoladominical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqsLRxXZyOrx1TqCYerJAne3TcNQn76as',
    appId: '1:371129962616:web:44b0566039ef79d2a29d8d',
    messagingSenderId: '371129962616',
    projectId: 'escoladominical-f0c5a',
    authDomain: 'escoladominical-f0c5a.firebaseapp.com',
    storageBucket: 'escoladominical-f0c5a.firebasestorage.app',
  );
}
